sudo: required
services:
  - docker

before_install:
  - docker build -t vivekdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vivekdocker/react-test npm test -- --coverage

after_success:
  - docker build -t vivekshankar/multi-client ./client
  - docker build -t vivekshankar/multi-nginx ./nginx
  - docker build -t vivekshankar/multi-server ./server
  - docker build -t vivekshankar/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push viveksome/multi-client
  - docker push viveksome/multi-nginx
  - docker push viveksome/multi-server
  - docker push viveksome/multi-worker